### ISSUE TITLE
MacOS / homebrew include path change needed?

### ISSUE THREAD

**Issue by slyrus** [rpav/cl-freetype2#12]
In order to get cl-freetype2 to work with my MacOS setup, I had to do the following. I would think that far more MacOS users have homebrew installed than MacPorts these days, BICBW.

diff --git i/src/ffi/grovel/grovel-freetype2.lisp w/src/ffi/grovel/grovel-freetype2.lisp
index a3aaa3d..84037ad 100644
--- i/src/ffi/grovel/grovel-freetype2.lisp
+++ w/src/ffi/grovel/grovel-freetype2.lisp
@@ -1,6 +1,8 @@
 (in-package :freetype2-types)
 
 (cc-flags #+darwin "-I/opt/local/include/freetype2"
+          #+darwin "-I/usr/local/Cellar/freetype/2.9.1/include/freetype2/"
+          #+darwin "-I/usr/local/Cellar/freetype/2.9.1/include/freetype2/freetype"
           #+freebsd "-I/usr/local/include/freetype2"
           #+(and windows x86-64) "-I/mingw64/include/freetype2"
           #+(and windows x86-64) "-Ic:/msys64/mingw64/include/freetype2"

**Comment by chuchana** [comment]
Just had that problem again. See #7 for a fix that probably works with both Homebrew and Macports.

**Comment by noelbenz** [comment]
Unfortunately I don't think that fixed it for Homebrew. Looks like Homebrew installs to /usr/local instead of /opt/local. Needed to add the following to get a successful build:

```
          #+darwin "-I/usr/local/include/freetype2"
          #+darwin "-I/usr/local/include/freetype2/freetype"
```

`/usr/local/include/freetype2` is symlinked to `/usr/local/Cellar/freetype/2.10.0/include/freetype2`. I'll open a PR for this addition.
